### ISSUE TITLE
Error consistently printing to console

### ISSUE THREAD

**Issue by codyburleson** [aidenlx/alx-folder-note#130]
Console error consistently printing to the console:

```
app.js:1 Failed to open view TypeError: Cannot read properties of undefined (reading 'navFileContainerEl')
    at t.eval (plugin:alx-folder-note:4821:45)
    at t.wrapper [as load] (plugin:alx-folder-note:4107:20)
    at t.<anonymous> (app.js:1:1402700)
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at app.js:1:236279
    at new Promise (<anonymous>)
    at v (app.js:1:236024)
    at t.open (app.js:1:1402572)
    at t.<anonymous> (app.js:1:1825868)
```

**Comment by FynnFreyer** [comment]
Can confirm, have the same thing happening.
Seems to be due to `fileExplorer.dom` being undefined.

I have added appropriate checks #133

**Comment by FynnFreyer** [comment]
With that patch applied, I don't get any errors, and the plugin seems to be working still. Haven't done extensive testing though (and also won't, except for just using it normally)

**Comment by MJHop** [comment]
I'm sorry for the stupid question.. but how do I add in this fix? Having the same issue and I uninstalled and reinstalled the plugin but it's still happening.

**Comment by SebastianMC** [comment]
Hi @MJHop 

It's been more than a month since your post here, but maybe this will be helpful also for others.

Please look at my longer [comment in issue 134](https://github.com/aidenlx/alx-folder-note/issues/134#issuecomment-1992661131). It contains instructions on how to easily install the patched version of `alx-folder-note` plugin, compatible with Obsidian 1.5.4 (and newer) by using the well known [BRAT](https://github.com/TfTHacker/obsidian42-brat) plugin.
